"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import Card from "@/components/Card";
import {
  AlertTriangle,
  ShieldAlert,
  FileText,
  CheckCircle2,
  ArrowRight,
  Stethoscope,
  AlertCircle,
} from "lucide-react";

export default function DisclaimerPage() {
  const [accepted, setAccepted] = useState(false);
  const router = useRouter();

  const handleContinue = () => {
    if (accepted) {
      router.push("/predict");
    }
  };

  return (
    <div className="max-w-3xl mx-auto space-y-8">
      {/* Header */}
      <div className="text-center">
        <div className="inline-flex items-center justify-center w-16 h-16 bg-[#FEF2F2] rounded-2xl mb-4">
          <ShieldAlert className="text-[#EF4444]" size={32} />
        </div>
        <h2 className="text-3xl font-bold text-[#111827] mb-3">
          Medical Disclaimer
        </h2>
        <p className="text-[#6B7280] max-w-xl mx-auto">
          Please read and accept the following terms before proceeding to the risk prediction tool
        </p>
      </div>

      {/* Important Notice */}
      <div className="p-6 rounded-xl bg-gradient-to-br from-[#FEF2F2] to-[#FEE2E2] border-2 border-[#EF4444]">
        <div className="flex items-start gap-4">
          <div className="p-2 bg-white rounded-lg shadow-sm">
            <AlertTriangle className="text-[#EF4444]" size={24} />
          </div>
          <div>
            <h3 className="text-lg font-bold text-[#111827] mb-2">
              Important: This is NOT a Medical Diagnostic Tool
            </h3>
            <p className="text-[#4B5563] leading-relaxed">
              CardioGuard AI is an <span className="font-semibold">educational machine learning tool</span> designed 
              for demonstration and learning purposes only. It does <span className="font-semibold">not</span> provide 
              medical diagnosis, treatment recommendations, or replace professional medical advice.
            </p>
          </div>
        </div>
      </div>

      {/* Key Points */}
      <Card>
        <div className="flex items-center gap-3 mb-6">
          <div className="p-2 bg-[#EEF2FF] rounded-lg">
            <FileText className="text-[#4F46E5]" size={24} />
          </div>
          <h3 className="text-xl font-bold text-[#111827]">
            Terms & Conditions
          </h3>
        </div>

        <div className="space-y-4">
          <div className="flex items-start gap-3 p-4 rounded-lg bg-[#F9FAFB] border border-[#E5E7EB]">
            <div className="w-6 h-6 bg-[#FEF2F2] rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">
              <span className="text-[#EF4444] text-xs font-bold">1</span>
            </div>
            <div>
              <p className="font-semibold text-[#111827] mb-1">
                Probabilistic Predictions
              </p>
              <p className="text-sm text-[#6B7280]">
                All predictions generated by this system are probabilistic estimates based on 
                machine learning algorithms and historical data patterns.
              </p>
            </div>
          </div>

          <div className="flex items-start gap-3 p-4 rounded-lg bg-[#F9FAFB] border border-[#E5E7EB]">
            <div className="w-6 h-6 bg-[#FEF2F2] rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">
              <span className="text-[#EF4444] text-xs font-bold">2</span>
            </div>
            <div>
              <p className="font-semibold text-[#111827] mb-1">
                Accuracy Limitations
              </p>
              <p className="text-sm text-[#6B7280]">
                Results may not be 100% accurate. The model has a 72.82% accuracy rate, 
                meaning approximately 27% of predictions may be incorrect.
              </p>
            </div>
          </div>

          <div className="flex items-start gap-3 p-4 rounded-lg bg-[#F9FAFB] border border-[#E5E7EB]">
            <div className="w-6 h-6 bg-[#FEF2F2] rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">
              <span className="text-[#EF4444] text-xs font-bold">3</span>
            </div>
            <div>
              <p className="font-semibold text-[#111827] mb-1">
                Not a Substitute for Medical Advice
              </p>
              <p className="text-sm text-[#6B7280]">
                This tool cannot replace professional medical evaluation. Results should not 
                be used to make health decisions without consulting a qualified healthcare provider.
              </p>
            </div>
          </div>

          <div className="flex items-start gap-3 p-4 rounded-lg bg-[#F9FAFB] border border-[#E5E7EB]">
            <div className="w-6 h-6 bg-[#FEF2F2] rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">
              <span className="text-[#EF4444] text-xs font-bold">4</span>
            </div>
            <div>
              <p className="font-semibold text-[#111827] mb-1">
                Educational Purpose Only
              </p>
              <p className="text-sm text-[#6B7280]">
                This system is intended for educational demonstration of machine learning 
                applications in healthcare, not for clinical use.
              </p>
            </div>
          </div>
        </div>
      </Card>

      {/* Professional Consultation */}
      <div className="p-6 rounded-xl bg-[#ECFDF5] border border-[#A7F3D0]">
        <div className="flex items-start gap-4">
          <div className="p-2 bg-white rounded-lg shadow-sm">
            <Stethoscope className="text-[#22C55E]" size={24} />
          </div>
          <div>
            <h3 className="text-lg font-bold text-[#111827] mb-2">
              Always Consult a Certified Medical Professional
            </h3>
            <p className="text-[#4B5563] leading-relaxed">
              For any health concerns, symptoms, or cardiovascular risk assessment, 
              please schedule an appointment with a qualified doctor, cardiologist, 
              or healthcare provider who can conduct proper medical examinations and tests.
            </p>
          </div>
        </div>
      </div>

      {/* Acceptance & Continue */}
      <Card>
        <div className="space-y-6">
          <div className="flex items-start gap-3 p-4 rounded-lg bg-[#F9FAFB] border-2 border-dashed border-[#E5E7EB] hover:border-[#4F46E5] transition-all">
            <input
              type="checkbox"
              id="acceptance"
              checked={accepted}
              onChange={(e) => setAccepted(e.target.checked)}
              className="w-5 h-5 mt-0.5 text-[#4F46E5] border-[#E5E7EB] rounded focus:ring-2 focus:ring-[#4F46E5] focus:ring-offset-2 cursor-pointer"
            />
            <label
              htmlFor="acceptance"
              className="text-[#111827] font-medium cursor-pointer flex-1"
            >
              I have read and understood the medical disclaimer. I acknowledge that this is 
              an educational tool and not a substitute for professional medical advice, 
              diagnosis, or treatment.
            </label>
          </div>

          <div className="flex items-center gap-4">
            <button
              disabled={!accepted}
              onClick={handleContinue}
              className={`
                flex-1 flex items-center justify-center gap-2 px-6 py-3.5 rounded-lg font-semibold text-white transition-all duration-200
                ${
                  accepted
                    ? "bg-[#4F46E5] hover:bg-[#4338CA] shadow-md hover:shadow-lg hover:scale-[1.02]"
                    : "bg-[#E5E7EB] cursor-not-allowed opacity-60"
                }
              `}
            >
              {accepted ? (
                <>
                  <CheckCircle2 size={20} />
                  Continue to Risk Prediction
                  <ArrowRight size={20} />
                </>
              ) : (
                <>
                  <AlertCircle size={20} />
                  Please Accept Terms to Continue
                </>
              )}
            </button>
          </div>

          {!accepted && (
            <p className="text-center text-sm text-[#9CA3AF]">
              You must accept the disclaimer before proceeding
            </p>
          )}
        </div>
      </Card>
    </div>
  );
}